public class StudentInfo {
    public StudentInfo() {

        system.debug('Welcome to student list');

    }

    public static void studentName() {
        List<string> listOfNames = new List<string>();
        listOfNames.add('Jack');
        listOfNames.add('Johny');
        listOfNames.add('Becc');
        listOfNames.add('Tom');
        listOfNames.add('Thomos');
        listOfNames.add('Olive');

        System.debug('These are the students name = ' + listOfNames);
        
    }
}
